{% set name = "sparsestack" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sparsestack-{{ version }}.tar.gz
  sha256: 96aca420bd8f536c7b6024055064a556b0fff28a0b63943497f60216da28f461

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numba
    - numpy
    - python >=3.7
    - scipy

test:
  imports:
    - sparsestack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/florian-huber/stacked-sparse-array
  summary: Python library to handle stacks of sparse COO arrays efficiently.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - florian-huber
